Repository mirage/irmin, pull requests merged in 2021-08, with the labels that each got.

#1490 Prepare 2.7.2 release
  CHANGES.md
  bench/irmin-pack/bench_common.ml
  bench/irmin-pack/bench_common.mli
  bench/irmin-pack/dune
  bench/irmin-pack/tree.ml
  irmin-bench.opam
  irmin-git.opam
  irmin-pack.opam
  irmin.opam
  src/irmin-pack/checks.ml
  src/irmin-pack/checks_intf.ml
  src/irmin-pack/ext.ml
  src/irmin-pack/mem/irmin_pack_mem.ml
  src/irmin-pack/reconstruct_index.ml
  src/irmin-pack/s.ml
  src/irmin-pack/traverse_pack_file.ml
  test/irmin-pack/cli/irmin-fsck-help.txt
  test/irmin-pack/test_existing_stores.ml
Labels: maintenance

#1391 irmin-fsck: traverse head commit for stats
  CHANGES.md
  src/irmin-pack/checks.ml
  src/irmin-pack/checks_intf.ml
  src/irmin-pack/ext.ml
  src/irmin-pack/inode.ml
  src/irmin-pack/inode_intf.ml
  src/irmin-pack/layered/ext_layered.ml
  src/irmin-pack/mem/irmin_pack_mem.ml
  src/irmin-pack/s.ml
  src/irmin/object_graph.ml
  src/irmin/object_graph_intf.ml
  src/irmin/store.ml
  src/irmin/store_intf.ml
  test/irmin-pack/cli/generate.ml
  test/irmin-pack/cli/irmin-fsck-help.txt
  test/irmin-pack/cli/stat.t/run.t
  test/irmin-pack/test_inode.ml
Labels: performance

#1503 Avoid flaky usage of [@tailcall]
  src/irmin-pack/IO.ml
  src/irmin-pack/inode.ml
  src/irmin/tree.ml
Labels: no-changelog-needed

#1507 Fix re-release instructions to include re-publishing distribution
  RELEASE.md
Labels: no-changelog-needed
