Repository mirage/irmin, pull requests merged in 2021-11, with the labels that each got.

#1573 Rewrite README.md
  README.md
  logo.svg
Labels: no-changelog-needed

#1589 Standardize tree.ml calls to ok
  src/irmin/tree.ml
Labels: no-changelog-needed

#1581 irmin-test: disable flaky test 'Watch.Basic operations'
  src/irmin-test/store_watch.ml
Labels: no-changelog-needed

#1577 irmin-pack: inline a more efficient codec for Index entries
  CHANGES.md
  src/irmin-pack/pack_index.ml
  src/irmin-pack/pack_value.ml
  src/irmin-pack/pack_value_intf.ml
Labels: performance

#1592 irmin-pack: avoid unnecessary duplication of the Tezos config
  bench/irmin-pack/bench_common.ml
  bench/irmin-pack/dune
  src/irmin-unix/dune
  src/irmin-unix/resolver.ml
  test/irmin-bench/replay.ml
  test/irmin-pack/common.ml
  test/irmin-pack/dune
  test/irmin-pack/layered.ml
  test/irmin-pack/multiple_instances.ml
Labels: no-changelog-needed

#1593 Adapt to index#366
  irmin-pack.opam
  src/irmin-pack/pack_index_intf.ml
Labels: no-changelog-needed

#1547 Adapt to mirage/repr#81 (improved binary decoder type)
  bench/irmin-pack/trace_common.ml
  irmin-pack.opam
  irmin.opam
  src/irmin-chunk/irmin_chunk.ml
  src/irmin-git/commit.ml
  src/irmin-git/contents.ml
  src/irmin-git/node.ml
  src/irmin-pack/atomic_write.ml
  src/irmin-pack/dict.ml
  src/irmin-pack/inode.ml
  src/irmin-pack/pack_index.ml
  src/irmin-pack/pack_store.ml
  src/irmin-pack/pack_value.ml
  src/irmin-pack/pack_value_intf.ml
  src/irmin-pack/traverse_pack_file.ml
  src/irmin/commit.ml
  src/irmin/hash.ml
  src/irmin/node.ml
  test/irmin-pack/common.ml
  test/irmin-pack/test_inode.ml
Labels: no-changelog-needed

#1604 irmin-test: disable more flaky tests
  src/irmin-test/store.ml
Labels: no-changelog-needed

#1610 simplify instantiation of portable nodes
  src/irmin-git/backend.ml
  src/irmin-git/irmin_git.ml
  src/irmin-http/irmin_http.ml
Labels: no-changelog-needed

#1602 Fix cascading fails
  src/irmin-test/common.ml
  test/irmin-pack/test_pack.ml
Labels: no-changelog-needed

#1616 Bench Pretty Printer support for hackmd format
  CHANGES.md
  bench/irmin-pack/trace_stat_summary_pp.ml
Labels: design

#1617 Expose Irmin_unix.Resolver.Store impl and remote fields
  src/irmin-unix/resolver.ml
  src/irmin-unix/resolver.mli
Labels: no-changelog-needed

#1630 Avoid use of deprecated `Lwt_main.yield`
  src/irmin-test/store.ml
  src/irmin-test/store_watch.ml
Labels: no-changelog-needed

#1628 [2.9] disable flaky tests
  src/irmin-test/store.ml
  src/irmin-test/store_watch.ml
Labels: no-changelog-needed

#1631 2.10 disable flaky tests
  src/irmin-test/store.ml
  src/irmin-test/store_watch.ml
Labels: no-changelog-needed

#1638 irmin-unix: Update `Irmin_unix.Resolver.Store.create` to use `hash` argument
  src/irmin-unix/resolver.ml
  test/irmin-unix/test_command_line.t
Labels: no-changelog-needed

#1612 irmin: have a more complete API for portable nodes
  src/irmin-pack/inode.ml
  src/irmin/node.ml
  src/irmin/node_intf.ml
Labels: no-changelog-needed

#1639 irmin-pack: more descriptive failure when reading an incorrect IO offset
  src/irmin-pack/IO.ml
Labels: no-changelog-needed

#1640 irmin-pack: support generic-keyed stores in replay
  bench/irmin-pack/bench_common.ml
  bench/irmin-pack/bench_common.mli
  bench/irmin-pack/layers.ml
  bench/irmin-pack/trace_collection.ml
  bench/irmin-pack/trace_replay.ml
  bench/irmin-pack/trace_replay_intf.ml
  bench/irmin-pack/tree.ml
Labels: no-changelog-needed

#1635 irmin-pack: collect location information for `find` operations
  bench/irmin-pack/trace_collection.ml
  bench/irmin-pack/trace_definitions.ml
  bench/irmin-pack/trace_stat_summary.ml
  bench/irmin-pack/trace_stat_summary_cb.ml
  bench/irmin-pack/trace_stat_summary_pp.ml
  src/irmin-pack/pack_store.ml
  src/irmin-pack/stats.ml
  src/irmin-pack/stats.mli
  test/irmin-bench/replay.ml
Labels: no-changelog-needed

#1643 irmin-pack: provide utility functions over value kinds
  src/irmin-pack/pack_value.ml
  src/irmin-pack/pack_value_intf.ml
  src/irmin-pack/traverse_pack_file.ml
Labels: no-changelog-needed

#1642 irmin-pack: refactor inode tests to not use unfindable contents keys
  test/irmin-pack/test_inode.ml
Labels: no-changelog-needed
