Repository mirage/irmin, pull requests merged in 2022-03, with the labels that each got.

#1796 Fix ci
  test/irmin-unix/test_command_line.t
Labels: no-changelog-needed

#1757 Expose a type for snapshots in inodes
  CHANGES.md
  src/irmin-pack/dune
  src/irmin-pack/inode.ml
  src/irmin-pack/inode_intf.ml
  src/irmin-pack/mem/irmin_pack_mem.ml
  src/irmin-pack/pack_store_intf.ml
  src/irmin-pack/s.ml
  src/irmin-pack/unix/ext.ml
  src/irmin-pack/unix/inode.ml
  src/irmin-pack/unix/inode.mli
  src/irmin-pack/unix/pack_index_intf.ml
  src/irmin-pack/unix/pack_store.ml
  src/irmin-pack/unix/snapshot.ml
  src/irmin-pack/unix/snapshot.mli
  src/irmin-pack/unix/snapshot_intf.ml
  test/irmin-pack/dune
  test/irmin-pack/test_pack.ml
  test/irmin-pack/test_snapshot.ml
Labels: area/backend, users/tezos

#1750 Overhaul GraphQL test suite
  src/irmin-graphql/server.ml
  test/irmin-graphql/common.ml
  test/irmin-graphql/common.mli
  test/irmin-graphql/test.ml
Labels: no-changelog-needed, type/tests

#1801 Update release doc
  RELEASE.md
Labels: no-changelog-needed
