Repository mirage/irmin, pull requests merged in 2022-04, with the labels that each got.

#1754 Upgrade to ocamlformat.0.21.0
  .ocamlformat
  bench/irmin-pack/trace_stat_summary_pp.ml
  src/irmin/indexable_intf.ml
  test/irmin-graphql/common.mli
  test/irmin/test_tree.ml
Labels: no-changelog-needed

#1797 Enable irmin-fsck for tezos stores
  test/irmin-tezos/irmin_fsck.ml
Labels: no-changelog-needed

#1820 docs: fix code typo
  README_PPX.md
Labels: type/bug, no-changelog-needed, area/ci-cb

#1819 docs: remove basics reference
  src/irmin/irmin.mli
Labels: type/doc, no-changelog-needed, area/backend

#1817 Introduce the new stats interface
  CHANGES.md
  bench/irmin-pack/trace_collection.ml
  src/irmin-pack/stats.ml
  src/irmin-pack/stats.mli
  src/irmin-pack/unix/import.ml
  src/irmin-pack/unix/irmin_pack_unix.ml
  src/irmin-pack/unix/pack_store.ml
  src/irmin-pack/unix/stats.ml
  src/irmin-pack/unix/stats.mli
  src/irmin/irmin.ml
  src/irmin/irmin.mli
  src/irmin/metrics.ml
  src/irmin/metrics.mli
  test/irmin-bench/replay.ml
Labels: type/feature, type/refactor, area/bench, area/core

#1827 Remove constraint for cmdliner
  irmin-bench.opam
Labels: no-changelog-needed

#1808 irmin-unix: Add ability to load contents/hash/store types from Dynlink plugin
  CHANGES.md
  examples/plugin/README.md
  examples/plugin/dune
  examples/plugin/plugin.ml
  examples/plugin/plugin.t
  src/irmin-unix/dune
  src/irmin-unix/resolver.ml
  src/irmin-unix/resolver.mli
Labels: area/cli
