Repository mirage/irmin, pull requests merged in 2022-02, with the labels that each got.

#1744 irmin: Improve error handling in Tree
  CHANGES.md
  src/irmin/tree.ml
  src/irmin/tree_intf.ml
Labels: feature/merkle-proofs

#1745 irmin: Improve cache usage in Tree
  src/irmin/tree.ml
Labels: no-changelog-needed, feature/merkle-proofs

#1746 irmin: Add `with_handler` and `head` to `Node_portable`
  CHANGES.md
  src/irmin-pack/inode.ml
  src/irmin-pack/inode_intf.ml
  src/irmin/node.ml
  src/irmin/node_intf.ml
Labels: feature/merkle-proofs

#1749 irmin: Trees carry a placeholder proof env
  src/irmin/tree.ml
Labels: no-changelog-needed, feature/merkle-proofs

#1755 irmin: Portable in tree
  src/irmin-test/store.ml
  src/irmin/node.ml
  src/irmin/node_intf.ml
  src/irmin/tree.ml
  src/irmin/tree_intf.ml
  test/irmin/test_tree.ml
Labels: no-changelog-needed, feature/merkle-proofs

#1760 irmin-bench: Enforce certain configurations for the replays
  bench/irmin-pack/tree.ml
Labels: no-changelog-needed

#1715 Prefix the prehash for default contents, nodes and commits
  CHANGES.md
  src/irmin-test/store.ml
  src/irmin/commit.ml
  src/irmin/commit_intf.ml
  src/irmin/contents.ml
  src/irmin/contents_intf.ml
  src/irmin/node.ml
  src/irmin/node_intf.ml
  test/irmin-chunk/test.ml
  test/irmin-pack/common.ml
  test/irmin-pack/common.mli
  test/irmin-pack/test_existing_stores.ml
  test/irmin-pack/test_inode.ml
  test/irmin-pack/test_pack.ml
Labels: type/bug, area/backend

#1776 irmin-unix: Fix issues with commands that use the remote term
  CHANGES.md
  src/irmin-unix/cli.ml
  src/irmin-unix/resolver.ml
  src/irmin-unix/resolver.mli
  test/irmin-unix/test_command_line.t
Labels: type/bug, area/cli

#1778 irmin-unix: Update default Mimic.ctx
  CHANGES.md
  examples/push.ml
  examples/sync.ml
  irmin-git.opam
  irmin-unix.opam
  src/irmin-git/dune
  src/irmin-graphql/server.ml
  src/irmin-graphql/server.mli
  src/irmin-mirage/graphql/irmin_mirage_graphql.ml
  src/irmin-unix/cli.ml
  src/irmin-unix/dune
  src/irmin-unix/resolver.ml
  src/irmin-unix/resolver.mli
  src/irmin-unix/xgit.ml
  src/irmin-unix/xgit_intf.ml
Labels: type/bug, area/git

#1713 Add libirmin
  CHANGES.md
  README_LIBIRMIN.md
  libirmin.opam
  src/libirmin/commit.ml
  src/libirmin/config.ml
  src/libirmin/dune
  src/libirmin/gen/dune
  src/libirmin/gen/generate.ml
  src/libirmin/info.ml
  src/libirmin/lib/dune
  src/libirmin/lib/libirmin.ml
  src/libirmin/libirmin_bindings.ml
  src/libirmin/path.ml
  src/libirmin/repo.ml
  src/libirmin/store.ml
  src/libirmin/tree.ml
  src/libirmin/type.ml
  src/libirmin/types.ml
  src/libirmin/types.mli
  src/libirmin/types_intf.ml
  src/libirmin/util.ml
  src/libirmin/value.ml
  test/libirmin/dune
  test/libirmin/greatest.h
  test/libirmin/test.c
Labels: area/bindings

#1782 Remove runtime dep on the ppx stack
  CHANGES.md
  examples/dune
  src/irmin-pack/dune
Labels: no-changelog-needed
