Repository mirage/irmin, pull requests merged in 2022-05, with the labels that each got.

#1834 irmin: remove redundant/unused module
  src/irmin/store.ml
Labels: no-changelog-needed

#1837 Add some doc in backend signature
  src/irmin/backend.ml
Labels: no-changelog-needed

#1838 layers: remove dead-code
  bench/irmin-pack/_layers.ml
  src/irmin-pack/_layered/IO_layers.ml
  src/irmin-pack/_layered/IO_layers.mli
  src/irmin-pack/_layered/checks.ml
  src/irmin-pack/_layered/conf.ml
  src/irmin-pack/_layered/conf.mli
  src/irmin-pack/_layered/dune
  src/irmin-pack/_layered/ext_layered.ml
  src/irmin-pack/_layered/ext_layered.mli
  src/irmin-pack/_layered/import.ml
  src/irmin-pack/_layered/inode_layers.ml
  src/irmin-pack/_layered/inode_layers.mli
  src/irmin-pack/_layered/inode_layers_intf.ml
  src/irmin-pack/_layered/irmin_pack_layered.ml
  src/irmin-pack/_layered/irmin_pack_layered.mli
  src/irmin-pack/_layered/layered_store.ml
  src/irmin-pack/_layered/layered_store.mli
  src/irmin-pack/_layered/layout.ml
  src/irmin-pack/_layered/s.ml
  test/irmin-pack/_layered.ml
Labels: no-changelog-needed

#1842 Remove deps on memtrace
  bench/irmin-pack/trace_replay.ml
  bench/irmin-pack/trace_stat_summary.ml
  irmin-bench.opam
Labels: no-changelog-needed

#1849 Add _metrics to gitignore
  .gitignore
Labels: no-changelog-needed

#1795 Refactor `Tree.export`'s `on_node`
  CHANGES.md
  src/irmin-test/store.ml
  src/irmin/tree.ml
  test/irmin/test_tree.ml
Labels: feature/layered-store

#1851 irmin-pack: Rename IO to io_legacy
  src/irmin-pack/atomic_write.ml
  src/irmin-pack/io_legacy.ml
  src/irmin-pack/io_legacy.mli
  src/irmin-pack/io_legacy_intf.ml
  src/irmin-pack/irmin_pack.ml
  src/irmin-pack/irmin_pack_intf.ml
  src/irmin-pack/unix/IO.mli
  src/irmin-pack/unix/atomic_write.ml
  src/irmin-pack/unix/checks.ml
  src/irmin-pack/unix/dict.ml
  src/irmin-pack/unix/dict_intf.ml
  src/irmin-pack/unix/ext.ml
  src/irmin-pack/unix/io_legacy.ml
  src/irmin-pack/unix/io_legacy.mli
  src/irmin-pack/unix/irmin_pack_unix.ml
  src/irmin-pack/unix/pack_dict.ml
  src/irmin-pack/unix/pack_store.ml
  src/irmin-pack/unix/snapshot.ml
  src/irmin-pack/unix/traverse_pack_file.ml
  test/irmin-pack/test_pack_version_bump.ml
Labels: no-changelog-needed, feature/layered-store
