Repository mirage/irmin, pull requests merged in 2022-08, with the labels that each got.

#2025 irmin-pack: use mmap for the mapping file
  src/irmin-pack/layout.ml
  src/irmin-pack/unix/dispatcher.ml
  src/irmin-pack/unix/dispatcher_intf.ml
  src/irmin-pack/unix/file_manager.ml
  src/irmin-pack/unix/file_manager_intf.ml
  src/irmin-pack/unix/gc.ml
  src/irmin-pack/unix/import.ml
  src/irmin-pack/unix/irmin_pack_unix.ml
  src/irmin-pack/unix/mapping_file.ml
  src/irmin-pack/unix/mapping_file.mli
  src/irmin-pack/unix/utils.ml
  test/irmin-pack/dune
  test/irmin-pack/test_mapping.ml
  test/irmin-pack/test_nearest_leq.ml
  test/irmin-pack/test_nearest_leq.mli
  test/irmin-pack/test_pack.ml
Labels: no-changelog-needed

#2003 bench: use high-level gc api for replays
  bench/irmin-pack/trace_replay.ml
  bench/irmin-pack/trace_replay_intf.ml
  bench/irmin-pack/tree.ml
  test/irmin-bench/replay.ml
Labels: no-changelog-needed

#2029 Move async out of IO
  src/irmin-pack/unix/async.ml
  src/irmin-pack/unix/async.mli
  src/irmin-pack/unix/async_intf.ml
  src/irmin-pack/unix/ext.ml
  src/irmin-pack/unix/io.ml
  src/irmin-pack/unix/io_intf.ml
  src/irmin-pack/unix/irmin_pack_unix.ml
  test/irmin-pack/test_gc.ml
Labels: no-changelog-needed

#2034 irmin-pack: refactor mapping file
  src/irmin-pack/layout.ml
  src/irmin-pack/unix/dispatcher.ml
  src/irmin-pack/unix/dispatcher_intf.ml
  src/irmin-pack/unix/errors.ml
  src/irmin-pack/unix/file_manager.ml
  src/irmin-pack/unix/file_manager_intf.ml
  src/irmin-pack/unix/gc.ml
  src/irmin-pack/unix/import.ml
  src/irmin-pack/unix/mapping_file.ml
  src/irmin-pack/unix/mapping_file.mli
  src/irmin-pack/unix/mapping_file_intf.ml
  src/irmin-pack/unix/utils.ml
  test/irmin-pack/test_mapping.ml
  test/irmin-pack/test_nearest_leq.ml
Labels: no-changelog-needed

#2037 irmin-pack: Add more stats in gc finalise
  bench/irmin-pack/trace_replay.ml
  bench/irmin-pack/trace_replay_intf.ml
  bench/irmin-pack/tree.ml
  examples/gc.ml
  src/irmin-pack/mem/irmin_pack_mem.ml
  src/irmin-pack/s.ml
  src/irmin-pack/unix/ext.ml
  test/irmin-bench/replay.ml
Labels: no-changelog-needed

#2038 irmin-tezos: make the cram tests more robust
  test/irmin-tezos/stat.t/run.t
Labels: no-changelog-needed

#2036 irmin-pack: change append only auto flush callback to pass `t`
  src/irmin-pack/unix/append_only_file.ml
  src/irmin-pack/unix/append_only_file_intf.ml
  src/irmin-pack/unix/ext.ml
  src/irmin-pack/unix/file_manager.ml
  src/irmin-pack/unix/gc.ml
  src/irmin-pack/unix/mapping_file.ml
Labels: no-changelog-needed, type/refactor

#2008 irmin-pack: remove allocations from lazy values
  src/irmin-pack/inode.ml
Labels: type/performance, no-changelog-needed

#2035 irmin-pack: use Lwt in gc finished callback
  bench/irmin-pack/trace_replay.ml
  bench/irmin-pack/trace_replay_intf.ml
  bench/irmin-pack/tree.ml
  examples/gc.ml
  src/irmin-pack/s.ml
  src/irmin-pack/unix/ext.ml
  test/irmin-bench/replay.ml
Labels: no-changelog-needed

#1986 Run transfer_exn in loop in GC child process
  src/irmin-pack/unix/gc.ml
Labels: no-changelog-needed

#2030 Enable libirmin for macos
  libirmin.opam
Labels: no-changelog-needed

#2041 Fix schema for GraphiQL interface
  src/irmin-graphql/server.ml
Labels: no-changelog-needed

#2016 irmin-pack: special-case Inode.list
  src/irmin-pack/inode.ml
Labels: type/performance, no-changelog-needed

#2009 irmin-pack: try to do not allocate while encoding inodes
  src/irmin-pack/inode.ml
Labels: type/performance, no-changelog-needed

#2015 irmin-pack: do not cache when hashing inodes
  src/irmin-pack/inode.ml
Labels: type/performance, no-changelog-needed

#2028 irmin: optimise V1.Hash.encode/decode
  src/irmin/hash.ml
Labels: type/performance, no-changelog-needed

#2058 Fix opam CI issues for 3.4 release
  examples/dune
  irmin-http.opam
  irmin-pack.opam
Labels: no-changelog-needed

#2061 docs: add missing step for release
  RELEASE.md
Labels: no-changelog-needed

#2051 irmin-pack: Cleanups in the file stack
  src/irmin-pack/unix/append_only_file_intf.ml
  src/irmin-pack/unix/async.ml
  src/irmin-pack/unix/control_file_intf.ml
  src/irmin-pack/unix/dispatcher.ml
  src/irmin-pack/unix/file_manager.ml
  src/irmin-pack/unix/file_manager_intf.ml
  src/irmin-pack/unix/mapping_file.ml
  src/irmin-pack/unix/mapping_file_intf.ml
Labels: no-changelog-needed

#2059 Improve constraints for GraphQL IO module
  src/irmin-graphql/server.mli
  src/irmin-graphql/unix/irmin_graphql_unix.mli
Labels: no-changelog-needed

#2048 irmin-pack: add fsync to gc process
  src/irmin-pack/unix/file_manager.ml
  src/irmin-pack/unix/gc.ml
  src/irmin-pack/unix/import.ml
  src/irmin-pack/unix/mapping_file.ml
Labels: no-changelog-needed

#2062 small cleanups
  src/irmin-pack/unix/file_manager.ml
  src/irmin-pack/unix/file_manager_intf.ml
Labels: no-changelog-needed

#2063 irmin-pack: extract GC logic from ext
  src/irmin-pack/unix/ext.ml
  src/irmin-pack/unix/gc.ml
  src/irmin-pack/unix/gc.mli
  src/irmin-pack/unix/gc_intf.ml
  test/irmin-pack/test_gc.ml
Labels: no-changelog-needed
