Repository mirage/irmin, pull requests merged in 2022-01, with the labels that each got.

#1689 Small diffs in pack
  src/irmin-pack/IO.ml
  src/irmin-pack/atomic_write.ml
  src/irmin-pack/dict.ml
  src/irmin-pack/pack_store.ml
Labels: no-changelog-needed

#1546 Fix some Odoc errors
  src/irmin-chunk/irmin_chunk.mli
  src/irmin-containers/counter.mli
  src/irmin-git/irmin_git_intf.ml
  src/irmin-unix/irmin_unix.mli
  src/irmin/atomic_write_intf.ml
  src/irmin/contents_intf.ml
  src/irmin/hash_intf.ml
  src/irmin/indexable_intf.ml
  src/irmin/info_intf.ml
  src/irmin/logging_intf.ml
  src/irmin/node_intf.ml
  src/irmin/path_intf.ml
  src/irmin/store_intf.ml
  src/irmin/store_properties_intf.ml
  src/irmin/tree_intf.ml
Labels: no-changelog-needed

#1681 irmin: mark as incompatible with Odoc.2.0.{1,2}
  irmin.opam
Labels: no-changelog-needed

#1698 irmin-git: fix spurious warning when writing to a new branch
  src/irmin-git/atomic_write.ml
Labels: no-changelog-needed

#1675 Tests for issue #1658 "test migration of pack stores from V1 to V2"
  src/irmin-pack/irmin_pack_intf.ml
  test/irmin-pack/common.ml
  test/irmin-pack/common.mli
  test/irmin-pack/dune
  test/irmin-pack/test_existing_stores.ml
  test/irmin-pack/test_pack.ml
  test/irmin-pack/test_pack_version_bump.ml
  test/irmin-pack/test_pack_version_bump.mli
Labels: no-changelog-needed

#991 Use MDX to test the README example
  README.md
  dune
  dune-project
  examples/readme.ml
  irmin.opam
Labels: no-changelog-needed

#1608 CLI: Update watch command
  CHANGES.md
  src/irmin-unix/cli.ml
Labels: CLI

#1702 Add `bisect_ppx` instrumentation to all libraries
  .github/workflows/coverage.yml
  .gitignore
  README.md
  bench/irmin-pack/dune
  codecov.yml
  irmin.opam
  ppx_irmin.opam
  src/irmin-chunk/dune
  src/irmin-containers/dune
  src/irmin-fs/dune
  src/irmin-git/dune
  src/irmin-graphql/dune
  src/irmin-http/dune
  src/irmin-layers/dune
  src/irmin-mirage/dune
  src/irmin-mirage/git/dune
  src/irmin-mirage/graphql/dune
  src/irmin-pack/dune
  src/irmin-pack/mem/dune
  src/irmin-test/dune
  src/irmin-tezos/dune
  src/irmin-unix/dune
  src/irmin/dune
  src/ppx_irmin/dune
Labels: no-changelog-needed

#1541 irmin-pack: replace ad-hoc progress bar printers with Progress
  src/irmin-pack/checks.ml
  src/irmin-pack/ext.ml
  src/irmin-pack/irmin_pack.ml
  src/irmin-pack/irmin_pack_intf.ml
  src/irmin-pack/traverse_pack_file.ml
  src/irmin-pack/utils.ml
  test/irmin-pack/dune
  test/irmin-pack/test.ml
  test/irmin-pack/test_utils.ml
Labels: no-changelog-needed

#1704 irmin-test: guard `Random.self_init` behind run
  src/irmin-test/common.ml
  src/irmin-test/irmin_test.mli
  src/irmin-test/store.ml
  src/irmin-test/store.mli
Labels: no-changelog-needed

#1705 Run code coverage on pushes to the `main` branch too
  .github/workflows/coverage.yml
Labels: no-changelog-needed

#1694 [2.10] Fix Tree.fold s390x
  irmin-git.opam
  irmin.opam
  src/irmin/tree.ml
  test/irmin-git/dune
Labels: type/bug, area/ci-cb

#1709 opam fixes
  irmin-http.opam
Labels: no-changelog-needed

#1672 irmin-pack: Fix inode's find starting depth
  src/irmin-pack/inode.ml
Labels: no-changelog-needed

#1714 Only run code coverage action in mirage/irmin
  .github/workflows/coverage.yml
Labels: no-changelog-needed, area/ci-cb

#1711 irmin-pack: More security on inode depth
  CHANGES.md
  src/irmin-pack/ext.ml
  src/irmin-pack/inode.ml
  src/irmin-pack/inode_intf.ml
  src/irmin/store_intf.ml
Labels: type/feature, feature/merkle-proofs

#1556 Upgrade to ocamlformat.0.20.0
  .ocamlformat
  bench/irmin-pack/trace_stat_summary_cb.ml
  src/irmin-git/commit.ml
  src/irmin-http/irmin_http.ml
  src/irmin-pack/checks_intf.ml
  src/irmin-pack/inode.ml
  src/irmin-test/common.ml
  src/irmin-test/layered_store.ml
  src/irmin-test/store_graph.ml
  src/irmin-test/store_watch.ml
  src/irmin/object_graph_intf.ml
  src/irmin/tree.ml
Labels: no-changelog-needed

#1716 Proof in nodes
  CHANGES.md
  src/irmin-git/node.ml
  src/irmin-pack/inode.ml
  src/irmin-pack/inode_intf.ml
  src/irmin/node.ml
  src/irmin/node_intf.ml
Labels: type/feature, feature/merkle-proofs

#1733 irmin-bench: use the latest version of Printbox
  bench/irmin-pack/dune
  bench/irmin-pack/trace_stat_summary_pp.ml
  irmin-bench.opam
Labels: no-changelog-needed

#1735 irmin: fix support for random-order unforced tree traversal
  src/irmin/tree.ml
  test/irmin-pack/test_tree.ml
Labels: no-changelog-needed

#1728 irmin: better signature for Tree.length (port from 2.10)
  bench/irmin-pack/trace_collection.ml
  src/irmin-test/store.ml
  src/irmin/tree.ml
  src/irmin/tree_intf.ml
Labels: no-changelog-needed

#1738 irmin-pack: improve test suite coverage of Conf values
  test/irmin-pack/test_pack.ml
Labels: no-changelog-needed

#1740 irmin-pack: refactor Inode.Compress types for clarity
  src/irmin-pack/inode.ml
Labels: no-changelog-needed

#1737 irmin: fix default `Node.Portable.{find,to_list}` implementations
  src/irmin-test/node.ml
  src/irmin/node.ml
  test/irmin/test.ml
Labels: no-changelog-needed

#1743 [2.10] opam: fix git lower bound
  irmin-git.opam
  irmin-http.opam
Labels: no-changelog-needed
