Repository mirage/irmin, pull requests merged in 2022-06, with the labels that each got.

#1794 Remove clear
  CHANGES.md
  src/irmin-chunk/irmin_chunk.ml
  src/irmin-fs/irmin_fs.ml
  src/irmin-git/backend.ml
  src/irmin-git/conf.ml
  src/irmin-git/conf.mli
  src/irmin-git/content_addressable.ml
  src/irmin-git/irmin_git.ml
  src/irmin-http/closeable.ml
  src/irmin-http/irmin_http.ml
  src/irmin-http/irmin_http_server.ml
  src/irmin-pack/conf.ml
  src/irmin-pack/indexable.ml
  src/irmin-pack/inode.ml
  src/irmin-pack/mem/indexable.ml
  src/irmin-pack/unix/pack_store.ml
  src/irmin-test/common.ml
  src/irmin-test/irmin_test.mli
  src/irmin-test/store.ml
  src/irmin-unix/resolver.ml
  src/irmin/append_only_intf.ml
  src/irmin/commit.ml
  src/irmin/conf.ml
  src/irmin/conf.mli
  src/irmin/content_addressable.ml
  src/irmin/content_addressable_intf.ml
  src/irmin/indexable.ml
  src/irmin/indexable_intf.ml
  src/irmin/mem/irmin_mem.ml
  src/irmin/node.ml
  test/irmin-fs/test_fs.ml
  test/irmin-git/test_git.ml
  test/irmin-git/test_git.mli
  test/irmin-http/test_http.ml
  test/irmin-mem/test_mem.ml
  test/irmin-pack/test_pack.ml
  test/irmin-pack/test_tree.ml
  test/irmin-unix/test_unix.ml
  test/irmin/generic-key/test_inlined_contents.ml
  test/irmin/generic-key/test_store_offset.ml
Labels: feature/layered-store

#1853 irmin-pack: Fix version typerepr
  src/irmin-pack/version.ml
Labels: no-changelog-needed, feature/layered-store

#1884 Fix version bump tests
  src/irmin-pack/unix/errors_base.ml
  src/irmin-pack/unix/file_manager.ml
  src/irmin-pack/unix/file_manager_intf.ml
  test/irmin-pack/test_pack_version_bump.ml
Labels: no-changelog-needed

#1887 docs: fix typos
  src/irmin/store_intf.ml
Labels: no-changelog-needed

#1888 Expose Index.Checks
  src/irmin-pack/unix/pack_index_intf.ml
Labels: no-changelog-needed

#1894 Fix command-line documentation for --options flag
  src/irmin-unix/resolver.ml
Labels: no-changelog-needed

#1898 Fix snapshot
  src/irmin-pack/unix/pack_store.ml
  src/irmin-pack/unix/pack_store_intf.ml
  src/irmin-pack/unix/snapshot.ml
  src/irmin-pack/unix/snapshot_intf.ml
Labels: no-changelog-needed

#1892 Upgrade tests
  src/irmin-pack/unix/ext.mli
  src/irmin-pack/unix/irmin_pack_unix.ml
  test/irmin-pack/common.ml
  test/irmin-pack/common.mli
  test/irmin-pack/data/version_2_always/index/log
  test/irmin-pack/data/version_2_always/store.branches
  test/irmin-pack/data/version_2_always/store.dict
  test/irmin-pack/data/version_2_always/store.pack
  test/irmin-pack/data/version_2_minimal/index/log
  test/irmin-pack/data/version_2_minimal/store.branches
  test/irmin-pack/data/version_2_minimal/store.dict
  test/irmin-pack/data/version_2_minimal/store.pack
  test/irmin-pack/dune
  test/irmin-pack/test_existing_stores.ml
  test/irmin-pack/test_pack.ml
  test/irmin-pack/test_upgrade.ml
Labels: no-changelog-needed

#1901 docs: add documentation for `Tree.inspect`
  src/irmin/tree.ml
  src/irmin/tree_intf.ml
Labels: no-changelog-needed

#1913 Dangling parent of commits on which gc is called
  src/irmin-pack/indexing_strategy.ml
  src/irmin-pack/inode.ml
  src/irmin-pack/pack_value.ml
  src/irmin-pack/pack_value_intf.ml
  src/irmin-pack/unix/checks.ml
  src/irmin-pack/unix/gc.ml
  src/irmin-pack/unix/pack_store.ml
  src/irmin-pack/unix/snapshot.ml
  src/irmin-pack/unix/traverse_pack_file.ml
  test/irmin-pack/test_gc.ml
Labels: no-changelog-needed

#1933 irmin-pack: document `IO.Unix.close` implementation
  src/irmin-pack/unix/io.ml
Labels: no-changelog-needed

#1828 irmin-pack: remove hard-coded random tests
  test/irmin-pack/test_tree.ml
Labels: no-changelog-needed

#1921 Add new file_manager stats
  src/irmin-pack/unix/file_manager.ml
  src/irmin-pack/unix/stats.ml
  src/irmin-pack/unix/stats.mli
Labels: no-changelog-needed

#1916 Non blocking dummy gc
  bench/irmin-pack/trace_replay.ml
  bench/irmin-pack/trace_replay_intf.ml
  bench/irmin-pack/tree.ml
  src/irmin-pack/layout.ml
  src/irmin-pack/mem/irmin_pack_mem.ml
  src/irmin-pack/s.ml
  src/irmin-pack/unix/errors.ml
  src/irmin-pack/unix/errors_base.ml
  src/irmin-pack/unix/ext.ml
  src/irmin-pack/unix/file_manager.ml
  src/irmin-pack/unix/file_manager_intf.ml
  src/irmin-pack/unix/gc.ml
  test/irmin-bench/replay.ml
  test/irmin-pack/test_gc.ml
  test/irmin-pack/test_snapshot.ml
  test/irmin-pack/test_upgrade.ml
Labels: no-changelog-needed

#1936 Add tests for non blocking gc
  test/irmin-pack/test_gc.ml
Labels: no-changelog-needed

#1942 Finalise gc in bench replay
  bench/irmin-pack/trace_replay.ml
  bench/irmin-pack/trace_replay_intf.ml
  bench/irmin-pack/tree.ml
  src/irmin-pack/unix/ext.ml
  test/irmin-bench/replay.ml
Labels: no-changelog-needed

#1935 irmin-pack.unix: refactor errors
  src/irmin-pack/unix/append_only_file.ml
  src/irmin-pack/unix/control_file.ml
  src/irmin-pack/unix/control_file_intf.ml
  src/irmin-pack/unix/errors.ml
  src/irmin-pack/unix/ext.ml
  src/irmin-pack/unix/file_manager.ml
  src/irmin-pack/unix/file_manager_intf.ml
  src/irmin-pack/unix/gc.ml
  src/irmin-pack/unix/io.ml
  src/irmin-pack/unix/io_errors.ml
  src/irmin-pack/unix/io_intf.ml
  src/irmin-pack/unix/irmin_pack_unix.ml
  src/irmin-pack/unix/pack_store.ml
  src/irmin-pack/unix/pack_store_intf.ml
  src/irmin-pack/unix/traverse_pack_file.ml
  test/irmin-pack/common.ml
  test/irmin-pack/common.mli
  test/irmin-pack/test_inode.ml
  test/irmin-pack/test_pack_version_bump.ml
Labels: no-changelog-needed

#1946 Gc process kills itself at the end
  src/irmin-pack/unix/ext.ml
  test/irmin-pack/test_gc.ml
Labels: no-changelog-needed

#1947 Add minimal indexing strategy to inode tests
  test/irmin-pack/test_inode.ml
Labels: no-changelog-needed
